import { ApiClient } from './api-client';
import { apiConfig } from '@/config/api';
import type {
  ReportMetadata,
  ScheduledReport,
  ReportExecutionLog,
  CustomReportConfig,
} from '@/types/reports';

export interface ReportQueryParams {
  [key: string]: string | number | boolean | undefined;
  startDate?: string;
  endDate?: string;
  branchId?: string;
  warehouseId?: string;
  supplierId?: string;
  customerId?: string;
  employeeId?: string;
  categoryId?: string;
  search?: string;
}

class ReportsService extends ApiClient {
  async getReportsList(): Promise<ReportMetadata[]> {
    try {
      const response = await this.get<ReportMetadata[]>(
        apiConfig.endpoints.reports.dashboard + '/list',
      );
      return response.data;
    } catch {
      return [
        {
          id: 'rep-sales-summary',
          name: 'Sales Summary Report',
          category: 'sales',
          description: 'Consolidated daily sales transactions, margins, and taxes.',
          frequency: 'daily',
          isFavorite: true,
          lastRun: '2026-07-16',
        },
        {
          id: 'rep-sales-product',
          name: 'Sales by Product',
          category: 'sales',
          description: 'Product-wise sales volumes, revenues, and discounts.',
          frequency: 'daily',
          isFavorite: true,
          lastRun: '2026-07-16',
        },
        {
          id: 'rep-sales-category',
          name: 'Sales by Category',
          category: 'sales',
          description: 'Distribution of sales across different product groups.',
          frequency: 'on-demand',
          lastRun: '2026-07-15',
        },
        {
          id: 'rep-purchase-summary',
          name: 'Purchase Summary Report',
          category: 'purchase',
          description: 'Overview of supplier purchase invoices and payments.',
          frequency: 'daily',
          isFavorite: true,
        },
        {
          id: 'rep-current-stock',
          name: 'Current Stock Report',
          category: 'inventory',
          description: 'Live quantity levels and valuations across all stores.',
          frequency: 'daily',
          isFavorite: true,
          lastRun: '2026-07-16',
        },
        {
          id: 'rep-low-stock',
          name: 'Low Stock Alerts',
          category: 'inventory',
          description: 'List of items below minimum safety stock levels.',
          frequency: 'daily',
        },
        {
          id: 'rep-top-customers',
          name: 'Top Customer Rankings',
          category: 'customer',
          description: 'Loyal customer spending values and visits frequency.',
          frequency: 'weekly',
        },
        {
          id: 'rep-supplier-due',
          name: 'Supplier Outstanding Dues',
          category: 'supplier',
          description: 'Pending payables list grouped by supplier.',
          frequency: 'weekly',
          lastRun: '2026-07-14',
        },
        {
          id: 'rep-employee-sales',
          name: 'Employee Sales Tracker',
          category: 'employee',
          description: 'POS transactions and revenue generated by cashier.',
          frequency: 'daily',
        },
        {
          id: 'rep-payments-summary',
          name: 'Payments Method Summary',
          category: 'payments',
          description: 'Payment modes breakdown (Card, Cash, Mobile).',
          frequency: 'daily',
        },
        {
          id: 'rep-vat-report',
          name: 'VAT/GST Tax Summary',
          category: 'tax',
          description: 'Input vs Output sales tax compliance ledger.',
          frequency: 'monthly',
          isFavorite: true,
          lastRun: '2026-07-01',
        },
        {
          id: 'rep-audit-log',
          name: 'System Activity Logs',
          category: 'audit',
          description: 'Security audit trail of user access and locks.',
          frequency: 'daily',
        },
      ];
    }
  }

  async getReportData(
    reportId: string,
    params?: ReportQueryParams,
  ): Promise<{ columns: string[]; rows: any[] }> {
    try {
      const response = await this.get<{ columns: string[]; rows: any[] }>(
        `${apiConfig.endpoints.reports.generate}/${reportId}`,
        params,
      );
      return response.data;
    } catch {
      // Simulate generic reports datasets
      if (reportId.includes('sales')) {
        return {
          columns: [
            'Date',
            'Invoice ID',
            'Product',
            'Category',
            'Quantity',
            'Revenue ($)',
            'Cashier',
          ],
          rows: [
            {
              Date: '2026-07-16',
              'Invoice ID': 'INV-9081',
              Product: 'Leather Wallet',
              Category: 'Accessories',
              Quantity: 2,
              'Revenue ($)': 150,
              Cashier: 'Tanvir H.',
            },
            {
              Date: '2026-07-16',
              'Invoice ID': 'INV-9082',
              Product: 'Running Shoes',
              Category: 'Footwear',
              Quantity: 1,
              'Revenue ($)': 120,
              Cashier: 'Nabila R.',
            },
            {
              Date: '2026-07-15',
              'Invoice ID': 'INV-9075',
              Product: 'Bluetooth Headset',
              Category: 'Electronics',
              Quantity: 3,
              'Revenue ($)': 270,
              Cashier: 'Tanvir H.',
            },
            {
              Date: '2026-07-15',
              'Invoice ID': 'INV-9076',
              Product: 'Cotton T-Shirt',
              Category: 'Apparel',
              Quantity: 5,
              'Revenue ($)': 125,
              Cashier: 'Arif A.',
            },
          ],
        };
      } else if (reportId.includes('purchase')) {
        return {
          columns: ['Date', 'PO Number', 'Supplier', 'Items Quantity', 'Total Cost ($)', 'Status'],
          rows: [
            {
              Date: '2026-07-16',
              'PO Number': 'PO-4512',
              Supplier: 'Global Importers Inc.',
              'Items Quantity': 150,
              'Total Cost ($)': 4500,
              Status: 'Received',
            },
            {
              Date: '2026-07-14',
              'PO Number': 'PO-4509',
              Supplier: 'Elite Distributors Ltd',
              'Items Quantity': 80,
              'Total Cost ($)': 2400,
              Status: 'Pending',
            },
            {
              Date: '2026-07-11',
              'PO Number': 'PO-4501',
              Supplier: 'Direct Tech Wholesale',
              'Items Quantity': 200,
              'Total Cost ($)': 6000,
              Status: 'Received',
            },
          ],
        };
      } else if (reportId.includes('inventory') || reportId.includes('stock')) {
        return {
          columns: [
            'SKU',
            'Product Name',
            'Warehouse',
            'Current Stock',
            'Safety Level',
            'Valuation ($)',
          ],
          rows: [
            {
              SKU: 'SKU-WAL-09',
              'Product Name': 'Leather Wallet',
              Warehouse: 'Main Hub A',
              'Current Stock': 450,
              'Safety Level': 50,
              'Valuation ($)': 13500,
            },
            {
              SKU: 'SKU-SHO-12',
              'Product Name': 'Running Shoes',
              Warehouse: 'Transit Depot B',
              'Current Stock': 12,
              'Safety Level': 20,
              'Valuation ($)': 960,
            },
            {
              SKU: 'SKU-BT-88',
              'Product Name': 'Bluetooth Headset',
              Warehouse: 'Main Hub A',
              'Current Stock': 85,
              'Safety Level': 15,
              'Valuation ($)': 5100,
            },
            {
              SKU: 'SKU-TSH-01',
              'Product Name': 'Cotton T-Shirt',
              Warehouse: 'Retail Shelf',
              'Current Stock': 15,
              'Safety Level': 30,
              'Valuation ($)': 225,
            },
          ],
        };
      } else if (reportId.includes('customer')) {
        return {
          columns: [
            'Customer ID',
            'Name',
            'Phone',
            'Orders Count',
            'Outstanding Debt ($)',
            'Loyalty Points',
          ],
          rows: [
            {
              'Customer ID': 'C-451',
              Name: 'Zayn Malik',
              Phone: '+88017123456',
              'Orders Count': 24,
              'Outstanding Debt ($)': 450,
              'Loyalty Points': 1200,
            },
            {
              'Customer ID': 'C-459',
              Name: 'Alia Bhatt',
              Phone: '+88018123456',
              'Orders Count': 18,
              'Outstanding Debt ($)': 0,
              'Loyalty Points': 840,
            },
            {
              'Customer ID': 'C-462',
              Name: 'Ranbir Kapoor',
              Phone: '+88019123456',
              'Orders Count': 9,
              'Outstanding Debt ($)': 120,
              'Loyalty Points': 310,
            },
          ],
        };
      } else if (reportId.includes('supplier')) {
        return {
          columns: [
            'Supplier ID',
            'Company Name',
            'Contact Person',
            'Purchase Invoices',
            'Outstanding Payables ($)',
          ],
          rows: [
            {
              'Supplier ID': 'S-201',
              'Company Name': 'Global Importers Inc.',
              'Contact Person': 'John Doe',
              'Purchase Invoices': 32,
              'Outstanding Payables ($)': 12500,
            },
            {
              'Supplier ID': 'S-205',
              'Company Name': 'Elite Distributors Ltd',
              'Contact Person': 'Jane Smith',
              'Purchase Invoices': 14,
              'Outstanding Payables ($)': 4300,
            },
            {
              'Supplier ID': 'S-210',
              'Company Name': 'Direct Tech Wholesale',
              'Contact Person': 'Bob Johnson',
              'Purchase Invoices': 8,
              'Outstanding Payables ($)': 0,
            },
          ],
        };
      } else if (reportId.includes('tax') || reportId.includes('vat') || reportId.includes('gst')) {
        return {
          columns: [
            'Tax Period',
            'Gross Sales ($)',
            'Output VAT ($)',
            'Gross Purchases ($)',
            'Input VAT ($)',
            'Net Payable ($)',
          ],
          rows: [
            {
              'Tax Period': 'July 2026',
              'Gross Sales ($)': 450000,
              'Output VAT ($)': 67500,
              'Gross Purchases ($)': 150000,
              'Input VAT ($)': 22500,
              'Net Payable ($)': 45000,
            },
            {
              'Tax Period': 'June 2026',
              'Gross Sales ($)': 380000,
              'Output VAT ($)': 57000,
              'Gross Purchases ($)': 120000,
              'Input VAT ($)': 18000,
              'Net Payable ($)': 39000,
            },
          ],
        };
      } else if (reportId.includes('audit') || reportId.includes('log')) {
        return {
          columns: ['Timestamp', 'User', 'Action', 'Module', 'IP Address', 'Status'],
          rows: [
            {
              Timestamp: '2026-07-16 11:20:44',
              User: 'admin@epos.com',
              Action: 'Period Lock Toggle',
              Module: 'Accounting',
              'IP Address': '192.168.1.5',
              Status: 'Success',
            },
            {
              Timestamp: '2026-07-16 10:14:12',
              User: 'clerk1@epos.com',
              Action: 'Void Receipt',
              Module: 'POS Terminal',
              'IP Address': '192.168.1.12',
              Status: 'Authorized',
            },
            {
              Timestamp: '2026-07-15 16:45:00',
              User: 'admin@epos.com',
              Action: 'Delete Product SKU',
              Module: 'Inventory',
              'IP Address': '192.168.1.5',
              Status: 'Success',
            },
          ],
        };
      } else {
        return {
          columns: ['Field A', 'Field B', 'Value'],
          rows: [
            { 'Field A': 'Data Point A1', 'Field B': 'Data Point B1', Value: 1200 },
            { 'Field A': 'Data Point A2', 'Field B': 'Data Point B2', Value: 850 },
          ],
        };
      }
    }
  }

  async getScheduledReports(): Promise<ScheduledReport[]> {
    try {
      const response = await this.get<ScheduledReport[]>(
        apiConfig.endpoints.reports.schedule + '/list',
      );
      return response.data;
    } catch {
      return [
        {
          id: 'sch-1',
          reportId: 'rep-sales-summary',
          reportName: 'Sales Summary Report',
          frequency: 'daily',
          emailList: ['executives@epos.com', 'finance@epos.com'],
          timeOfDay: '20:00',
          status: 'active',
          lastSent: '2026-07-16 20:01:10',
        },
        {
          id: 'sch-2',
          reportId: 'rep-current-stock',
          reportName: 'Current Stock Report',
          frequency: 'weekly',
          emailList: ['warehouse@epos.com'],
          timeOfDay: '09:00',
          status: 'active',
          lastSent: '2026-07-13 09:00:45',
        },
        {
          id: 'sch-3',
          reportId: 'rep-vat-report',
          reportName: 'VAT/GST Tax Summary',
          frequency: 'monthly',
          emailList: ['tax-audit@epos.com'],
          timeOfDay: '08:00',
          status: 'paused',
        },
      ];
    }
  }

  async createScheduledReport(
    data: Omit<ScheduledReport, 'id' | 'lastSent'>,
  ): Promise<ScheduledReport> {
    try {
      const response = await this.post<ScheduledReport>(
        apiConfig.endpoints.reports.schedule + '/create',
        data,
      );
      return response.data;
    } catch {
      return {
        ...data,
        id: `sch-${Math.floor(Math.random() * 1000)}`,
        status: 'active',
      };
    }
  }

  async updateScheduledReportStatus(id: string, status: 'active' | 'paused'): Promise<boolean> {
    try {
      await this.post(`${apiConfig.endpoints.reports.schedule}/status`, { id, status });
      return true;
    } catch {
      return true;
    }
  }

  async getExportLogs(): Promise<ReportExecutionLog[]> {
    try {
      const response = await this.get<ReportExecutionLog[]>(
        apiConfig.endpoints.reports.export + '/list',
      );
      return response.data;
    } catch {
      return [
        {
          id: 'log-1',
          reportId: 'rep-sales-summary',
          reportName: 'Sales Summary Report',
          format: 'pdf',
          generatedBy: 'admin@epos.com',
          timestamp: '2026-07-16 14:15:30',
          status: 'completed',
        },
        {
          id: 'log-2',
          reportId: 'rep-current-stock',
          reportName: 'Current Stock Report',
          format: 'xlsx',
          generatedBy: 'admin@epos.com',
          timestamp: '2026-07-16 11:10:44',
          status: 'completed',
        },
        {
          id: 'log-3',
          reportId: 'rep-audit-log',
          reportName: 'System Activity Logs',
          format: 'csv',
          generatedBy: 'auditor@epos.com',
          timestamp: '2026-07-15 17:30:15',
          status: 'completed',
        },
      ];
    }
  }
}

export const reportsService = new ReportsService();
