export const apiConfig = {
  baseURL: process.env['NEXT_PUBLIC_API_URL'] ?? 'http://localhost:4000/api/v1',
  timeout: 30_000,
  retries: 3,
  retryDelay: 1_000,
  endpoints: {
    auth: {
      login: '/auth/login',
      logout: '/auth/logout',
      refresh: '/auth/refresh',
      me: '/auth/me',
      forgotPassword: '/auth/forgot-password',
      resetPassword: '/auth/reset-password',
      changePassword: '/auth/change-password',
      verifyEmail: '/auth/verify-email',
      resendVerification: '/auth/resend-verification',
      twoFactor: '/auth/two-factor/verify',
      twoFactorSetup: '/auth/two-factor/setup',
      twoFactorDisable: '/auth/two-factor/disable',
    },
    users: '/users',
    profile: '/users/profile',
    avatar: '/users/profile/avatar',
    sessions: '/auth/sessions',
    roles: '/roles',
    permissions: '/permissions',
    workspaces: '/workspaces',
    products: '/products',
    categories: '/categories',
    brands: '/brands',
    units: '/units',
    customers: '/customers',
    suppliers: '/suppliers',
    supplierPayments: '/supplier-payments',
    employees: '/employees',
    auditLogs: '/audit-logs',
    activity: '/activity',
    loginHistory: '/login-history',
    userSessions: '/user-sessions',
    warehouses: '/warehouses',
    branches: '/branches',
    storageLocations: '/storage-locations',
    inventory: '/inventory',
    batches: '/batches',
    serials: '/serials',
    inventoryLedger: '/inventory-ledger',
    stockAlerts: '/stock-alerts',
    stockAdjustments: '/stock-adjustments',
    stockTransfers: '/stock-transfers',
    stockTakes: '/stock-takes',
    reconciliation: '/reconciliation',
    purchaseOrders: '/purchase-orders',
    goodsReceive: '/goods-receive',
    supplierInvoices: '/supplier-invoices',
    purchaseReturns: '/purchase-returns',
    supplierCreditNotes: '/supplier-credit-notes',
    supplierDebitNotes: '/supplier-debit-notes',
    pos: {
      checkout: '/pos/checkout',
      payments: '/pos/payments',
      receipts: '/pos/receipts',
      invoices: '/pos/invoices',
      cashDrawer: '/pos/cash-drawer',
    },
  },
} as const;

export type ApiConfig = typeof apiConfig;
