import {
  LayoutDashboard,
  ShoppingCart,
  Package,
  ShoppingBag,
  Users,
  Truck,
  BookOpen,
  BarChart3,
  Settings,
  Building2,
  Shield,
  Bell,
  Layers,
  Tag,
  Ruler,
  Network,
  Briefcase,
  UserCheck,
  KeyRound,
  Warehouse,
  Store,
  LayoutGrid,
  Sliders,
  ArrowLeftRight,
  ClipboardCheck,
  AlertOctagon,
  FileText,
  Scale,
  Undo2,
  FileWarning,
  CreditCard,
  Calendar,
  Printer,
  FileDown,
  SlidersHorizontal,
  type LucideIcon,
} from 'lucide-react';

export interface NavItem {
  id: string;
  label: string;
  href: string;
  icon: LucideIcon;
  badge?: string | number;
  children?: NavItem[];
  permission?: string;
  roles?: string[];
  isExternal?: boolean;
  isSeparator?: boolean;
}

export interface NavSection {
  id: string;
  label: string;
  items: NavItem[];
}

export const navigationConfig: NavSection[] = [
  {
    id: 'main',
    label: 'Main',
    items: [
      {
        id: 'dashboard',
        label: 'Dashboard',
        href: '/dashboard',
        icon: LayoutDashboard,
      },
    ],
  },
  {
    id: 'operations',
    label: 'Operations',
    items: [
      {
        id: 'pos',
        label: 'Point of Sale',
        href: '/pos',
        icon: ShoppingCart,
        permission: 'pos:view',
      },
      {
        id: 'sales',
        label: 'Sales',
        href: '/sales',
        icon: ShoppingBag,
        permission: 'sales:view',
      },
      {
        id: 'inventory',
        label: 'Inventory & Stock',
        href: '/inventory',
        icon: Package,
        permission: 'inventory:view',
        children: [
          {
            id: 'inventory-dashboard',
            label: 'Dashboard',
            href: '/inventory',
            icon: LayoutDashboard,
          },
          {
            id: 'stock-adjustments',
            label: 'Stock Adjustments',
            href: '/inventory/adjustments',
            icon: Sliders,
            permission: 'stock.view',
          },
          {
            id: 'stock-transfers',
            label: 'Stock Transfers',
            href: '/inventory/transfers',
            icon: ArrowLeftRight,
            permission: 'stock.view',
          },
          {
            id: 'cycle-count',
            label: 'Cycle Count',
            href: '/inventory/cycle-count',
            icon: ClipboardCheck,
            permission: 'inventory.stocktake',
          },
          {
            id: 'damage-loss',
            label: 'Damage & Loss',
            href: '/inventory/damage-loss',
            icon: AlertOctagon,
            permission: 'stock.view',
          },
        ],
      },
      {
        id: 'products',
        label: 'Products Catalog',
        href: '/products',
        icon: Tag,
        permission: 'inventory:view',
      },
      {
        id: 'categories',
        label: 'Categories',
        href: '/products/categories',
        icon: Layers,
        permission: 'category.read',
      },
      {
        id: 'brands',
        label: 'Brands',
        href: '/products/brands',
        icon: Tag,
        permission: 'brand.read',
      },
      {
        id: 'units',
        label: 'Units',
        href: '/products/units',
        icon: Ruler,
        permission: 'unit.read',
      },
      {
        id: 'purchase',
        label: 'Purchase',
        href: '/purchase',
        icon: Truck,
        permission: 'purchase:view',
        children: [
          {
            id: 'purchase-dashboard',
            label: 'Dashboard',
            href: '/purchase',
            icon: LayoutDashboard,
            permission: 'purchase:view',
          },
          {
            id: 'purchase-requisitions',
            label: 'Requisitions',
            href: '/purchase/requisitions',
            icon: FileText,
            permission: 'purchase:view',
          },
          {
            id: 'purchase-orders',
            label: 'Purchase Orders',
            href: '/purchase/orders',
            icon: Truck,
            permission: 'purchase:view',
          },
          {
            id: 'purchase-receive',
            label: 'Goods Receive (GRN)',
            href: '/purchase/receive',
            icon: Truck,
            permission: 'purchase.receive.view',
          },
          {
            id: 'purchase-invoices',
            label: 'Supplier Invoices',
            href: '/purchase/invoices',
            icon: FileText,
            permission: 'supplier.invoice.view',
          },
          {
            id: 'purchase-matching',
            label: 'Invoice Matching',
            href: '/purchase/matching',
            icon: Scale,
            permission: 'supplier.invoice.view',
          },
          {
            id: 'purchase-returns',
            label: 'Purchase Returns',
            href: '/purchase/returns',
            icon: Undo2,
            permission: 'purchase:view',
          },
          {
            id: 'purchase-credit-notes',
            label: 'Credit Notes',
            href: '/purchase/credit-notes',
            icon: FileWarning,
            permission: 'purchase:view',
          },
          {
            id: 'purchase-debit-notes',
            label: 'Debit Notes',
            href: '/purchase/debit-notes',
            icon: CreditCard,
            permission: 'purchase:view',
          },
        ],
      },
    ],
  },
  {
    id: 'management',
    label: 'Management',
    items: [
      {
        id: 'customers',
        label: 'Customers',
        href: '/customers',
        icon: Users,
        permission: 'customers:view',
      },
      {
        id: 'suppliers',
        label: 'Suppliers',
        href: '/suppliers',
        icon: Building2,
        permission: 'suppliers:view',
      },
      {
        id: 'warehouses',
        label: 'Warehouses',
        href: '/warehouses',
        icon: Warehouse,
        permission: 'warehouse.view',
      },
      {
        id: 'branches',
        label: 'Branches',
        href: '/branches',
        icon: Store,
        permission: 'branch.read',
      },
      {
        id: 'storage-locations',
        label: 'Storage Locations',
        href: '/storage-locations',
        icon: LayoutGrid,
        permission: 'warehouse.view',
      },
      {
        id: 'accounting',
        label: 'Accounting',
        href: '/accounting',
        icon: BookOpen,
        permission: 'accounting:view',
        children: [
          {
            id: 'accounting-dashboard',
            label: 'Dashboard',
            href: '/accounting',
            icon: LayoutDashboard,
          },
          {
            id: 'accounting-accounts',
            label: 'Chart of Accounts',
            href: '/accounting/accounts',
            icon: BookOpen,
          },
          {
            id: 'accounting-journals',
            label: 'Journal Entries',
            href: '/accounting/journals',
            icon: FileText,
          },
          {
            id: 'accounting-general-ledger',
            label: 'General Ledger',
            href: '/accounting/general-ledger',
            icon: Scale,
          },
          {
            id: 'accounting-account-ledger',
            label: 'Account Ledger',
            href: '/accounting/account-ledger',
            icon: FileText,
          },
          {
            id: 'accounting-income',
            label: 'Income Book',
            href: '/accounting/income',
            icon: BookOpen,
          },
          {
            id: 'accounting-expense',
            label: 'Expense Book',
            href: '/accounting/expense',
            icon: BookOpen,
          },
          {
            id: 'accounting-cash-book',
            label: 'Cash Book',
            href: '/accounting/cash-book',
            icon: BookOpen,
          },
          {
            id: 'accounting-bank-book',
            label: 'Bank Book',
            href: '/accounting/bank-book',
            icon: BookOpen,
          },
          {
            id: 'accounting-payment-vouchers',
            label: 'Payment Vouchers',
            href: '/accounting/payment-vouchers',
            icon: FileText,
          },
          {
            id: 'accounting-receipt-vouchers',
            label: 'Receipt Vouchers',
            href: '/accounting/receipt-vouchers',
            icon: FileText,
          },
        ],
      },
      {
        id: 'analytics',
        label: 'Business Analytics',
        href: '/analytics/dashboard',
        icon: BarChart3,
        permission: 'reports:view',
        children: [
          {
            id: 'analytics-dashboard',
            label: 'Executive Dashboard',
            href: '/analytics/dashboard',
            icon: LayoutDashboard,
          },
          {
            id: 'analytics-overview',
            label: 'Business Overview',
            href: '/analytics/overview',
            icon: BarChart3,
          },
          {
            id: 'analytics-sales',
            label: 'Sales Analytics',
            href: '/analytics/sales',
            icon: ShoppingBag,
          },
          {
            id: 'analytics-purchase',
            label: 'Purchase Analytics',
            href: '/analytics/purchase',
            icon: Truck,
          },
          {
            id: 'analytics-inventory',
            label: 'Inventory Analytics',
            href: '/analytics/inventory',
            icon: Package,
          },
          {
            id: 'analytics-customer',
            label: 'Customer Analytics',
            href: '/analytics/customer',
            icon: Users,
          },
          {
            id: 'analytics-supplier',
            label: 'Supplier Analytics',
            href: '/analytics/supplier',
            icon: Building2,
          },
          {
            id: 'analytics-branch',
            label: 'Branch Analytics',
            href: '/analytics/branch',
            icon: Store,
          },
          {
            id: 'analytics-warehouse',
            label: 'Warehouse Analytics',
            href: '/analytics/warehouse',
            icon: Warehouse,
          },
          {
            id: 'analytics-employee',
            label: 'Employee Analytics',
            href: '/analytics/employee',
            icon: UserCheck,
          },
        ],
      },
      {
        id: 'reports',
        label: 'Reports Center',
        href: '/reports',
        icon: FileText,
        permission: 'reports:view',
        children: [
          {
            id: 'reports-dashboard',
            label: 'Reports Dashboard',
            href: '/reports',
            icon: LayoutDashboard,
          },
          {
            id: 'reports-sales',
            label: 'Sales Reports',
            href: '/reports/sales',
            icon: ShoppingBag,
          },
          {
            id: 'reports-purchase',
            label: 'Purchase Reports',
            href: '/reports/purchase',
            icon: Truck,
          },
          {
            id: 'reports-inventory',
            label: 'Inventory Reports',
            href: '/reports/inventory',
            icon: Package,
          },
          {
            id: 'reports-customer',
            label: 'Customer Reports',
            href: '/reports/customer',
            icon: Users,
          },
          {
            id: 'reports-supplier',
            label: 'Supplier Reports',
            href: '/reports/supplier',
            icon: Building2,
          },
          {
            id: 'reports-employee',
            label: 'Employee Reports',
            href: '/reports/employee',
            icon: UserCheck,
          },
          {
            id: 'reports-payments',
            label: 'Payment Reports',
            href: '/reports/payments',
            icon: CreditCard,
          },
          {
            id: 'reports-tax',
            label: 'Tax Reports',
            href: '/reports/tax',
            icon: Shield,
          },
          {
            id: 'reports-audit',
            label: 'Audit Reports',
            href: '/reports/audit',
            icon: BookOpen,
          },
          {
            id: 'reports-custom',
            label: 'Custom Builder',
            href: '/reports/custom',
            icon: SlidersHorizontal,
          },
          {
            id: 'reports-export',
            label: 'Export Center',
            href: '/reports/export',
            icon: FileDown,
          },
          {
            id: 'reports-print',
            label: 'Print Center',
            href: '/reports/print',
            icon: Printer,
          },
          {
            id: 'reports-scheduled',
            label: 'Scheduled Reports',
            href: '/reports/scheduled',
            icon: Calendar,
          },
        ],
      },
      {
        id: 'bi',
        label: 'Executive BI',
        href: '/bi',
        icon: Scale,
        permission: 'reports:view',
        children: [
          {
            id: 'bi-dashboard',
            label: 'BI Dashboard',
            href: '/bi',
            icon: LayoutDashboard,
          },
          {
            id: 'bi-analytics',
            label: 'Advanced Analytics',
            href: '/bi/analytics',
            icon: SlidersHorizontal,
          },
          {
            id: 'bi-forecast',
            label: 'Projections Forecast',
            href: '/bi/forecast',
            icon: Calendar,
          },
          {
            id: 'bi-customer-insights',
            label: 'Customer Insights',
            href: '/bi/insights/customer',
            icon: Users,
          },
          {
            id: 'bi-supplier-insights',
            label: 'Supplier Insights',
            href: '/bi/insights/supplier',
            icon: Building2,
          },
          {
            id: 'bi-trends',
            label: 'Business Trends',
            href: '/bi/trends',
            icon: BarChart3,
          },
          {
            id: 'bi-saved',
            label: 'Saved Layouts',
            href: '/bi/saved',
            icon: LayoutDashboard,
          },
          {
            id: 'bi-widgets',
            label: 'Widget Library',
            href: '/bi/widgets',
            icon: Settings,
          },
        ],
      },
    ],
  },
  {
    id: 'administration',
    label: 'Administration',
    items: [
      {
        id: 'employees',
        label: 'Employees',
        href: '/employees',
        icon: UserCheck,
        permission: 'employee.read',
      },
      {
        id: 'users',
        label: 'User Accounts',
        href: '/users',
        icon: KeyRound,
        permission: 'user.read',
      },
      {
        id: 'roles',
        label: 'Roles & Permissions',
        href: '/roles',
        icon: Shield,
        permission: 'role.read',
      },
      {
        id: 'departments',
        label: 'Departments',
        href: '/departments',
        icon: Network,
        permission: 'employee.read',
      },
      {
        id: 'designations',
        label: 'Designations',
        href: '/designations',
        icon: Briefcase,
        permission: 'employee.read',
      },
    ],
  },
  {
    id: 'system',
    label: 'System',
    items: [
      {
        id: 'notifications',
        label: 'Notifications',
        href: '/notifications',
        icon: Bell,
      },
      {
        id: 'settings',
        label: 'Settings',
        href: '/settings/profile',
        icon: Settings,
      },
    ],
  },
];
